
export const ADD_TODO="ADD_TODO";
export const REMOVE_TODO="REMOVE_TODO";
export const TOGGLE_TODO="TOGGLE_TODO";
export const TOGGLE_ALLTODO="TOGGLE_ALLTODO";
export const SET_VISIBILITY="SET_VISIBILITY";
export const REMOVE_COMPLETED="REMOVE_COMPLETED";
export const UPDATE_TODO="UPDATE_TODO";